name: CI

on:
  push:
    branches: [stable, dev]
  pull_request:
    branches: [stable, dev]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        run: |
          sudo apt-get install -y shellcheck
          shellcheck fix_wsl2_networking.sh
